// Generated by CoffeeScript 1.3.3

Ext.define('WSI.view.AccountContainer', {
  extend: 'Ext.Container',
  xtype: 'accountcontainer',
  id: 'accountcontainer',
  requires: ['WSI.view.Account', 'WSI.view.Activity', 'WSI.view.Following'],
  config: {
    padding: 0,
    layout: {
      type: 'card'
    },
    listeners: {
      activate: function() {
        return this.getAt(1).setActiveItem(this.getAt(1).getActiveItem());
      }
    },
    items: [
      {
        xtype: 'toolbar',
        id: 'sliderMenuSettings',
        docked: 'top',
        ui: 'orange',
        height: 35,
        layout: {
          type: 'hbox',
          pack: 'center'
        },
        html: '<div class="sliderMenuSettingsPointer"></div>',
        items: [
          {
            xtype: 'component',
            html: 'Account',
            width: '33%',
            padding: '8 0 8 0',
            style: {
              textAlign: 'center'
            },
            listeners: {
              tap: {
                element: 'element',
                fn: function(e) {
                  return this.getParent().getParent().getAt(1).setActiveItem(0);
                }
              }
            }
          }, {
            xtype: 'component',
            html: 'Activity',
            width: '33%',
            padding: '8 0 8 0',
            style: {
              textAlign: 'center'
            },
            listeners: {
              tap: {
                element: 'element',
                fn: function(e) {
                  if (window.localStorage.getItem('wsitoken') != null) {
                    return this.getParent().getParent().getAt(1).setActiveItem(1);
                  } else {
                    return navigator.notification.alert('', (function() {}), 'Please Login');
                  }
                }
              }
            }
          }, {
            xtype: 'component',
            html: 'Following',
            width: '33%',
            padding: '8 0 8 0',
            style: {
              textAlign: 'center'
            },
            listeners: {
              tap: {
                element: 'element',
                fn: function(e) {
                  if (window.localStorage.getItem('wsitoken') != null) {
                    return this.getParent().getParent().getAt(1).setActiveItem(2);
                  } else {
                    return navigator.notification.alert('', (function() {}), 'Please Login');
                  }
                }
              }
            }
          }
        ]
      }, {
        xtype: 'carousel',
        fullscreen: true,
        ui: 'light',
        direction: 'horizontal',
        items: [
          {
            xtype: 'container',
            layout: 'card',
            listeners: {
              activate: function() {
                if (this.getItems().items.length === 0) {
                  this.add({
                    xtype: "account"
                  });
                  return this.getItems().getAt(0).show();
                }
              },
              deactivate: function() {
                return this.removeAll(true, true);
              }
            }
          }, {
            xtype: 'container',
            layout: 'card',
            listeners: {
              activate: function() {
                if (this.getItems().items.length === 0) {
                  this.add({
                    xtype: "activity"
                  });
                  return this.getItems().getAt(0).show();
                }
              },
              deactivate: function() {
                return this.removeAll(true, true);
              }
            }
          }, {
            xtype: 'container',
            layout: 'card',
            listeners: {
              activate: function() {
                if (this.getItems().items.length === 0) {
                  this.add({
                    xtype: "following"
                  });
                  return this.getItems().getAt(0).show();
                }
              },
              deactivate: function() {
                return this.removeAll(true, true);
              }
            }
          }
        ],
        listeners: {
          dragstart: {
            element: 'element',
            fn: function(e) {
              if (!(window.localStorage.getItem('wsitoken') != null)) {
                return false;
              }
            }
          },
          drag: {
            element: 'element',
            fn: function(e) {
              if (!(window.localStorage.getItem('wsitoken') != null)) {
                return false;
              }
            }
          },
          dragend: {
            element: 'element',
            fn: function(e) {
              if (!(window.localStorage.getItem('wsitoken') != null)) {
                return false;
              }
            }
          },
          activeitemchange: function(container, value, oldValue, eOpts) {
            var tabPos, _ref;
            tabPos = [16, 50, 82];
            return (_ref = document.getElementsByClassName('sliderMenuSettingsPointer')[0]) != null ? _ref.style.left = tabPos[container.getActiveIndex()] + '%' : void 0;
          },
          scope: this
        }
      }
    ]
  },
  initialize: function() {
    return this.callParent(arguments);
  }
});
