// Generated by CoffeeScript 1.3.3

Ext.define('WSI.view.TopToolbar', {
  extend: 'Ext.Toolbar',
  xtype: 'toptoolbar',
  config: {
    docked: 'top',
    ui: 'blue',
    height: 'auto',
    minHeight: 'auto',
    title: '&nbsp;'
  },
  initialize: function() {
    var createEventButton, homeButton, moreActionsButton;
    this.callParent(arguments);
    homeButton = {
      xtype: 'button',
      id: 'homeButton',
      cls: 'x-button-cback',
      text: ' ',
      hidden: true,
      dest: 0,
      busyHandling: false,
      handler: this.onHomeButtonTap,
      scope: this
    };
    createEventButton = {
      xtype: 'button',
      id: 'createEventButton',
      cls: 'x-button-create',
      text: ' ',
      handler: this.onCreateEventButtonTap,
      scope: this
    };
    moreActionsButton = {
      xtype: 'button',
      id: 'moreActionsButton',
      cls: 'x-button-more-actions',
      hidden: true,
      text: ' ',
      handler: function() {
        return this.fireEvent('moreActionsButtonTap');
      },
      scope: this
    };
    return this.add([
      homeButton, {
        xtype: 'spacer'
      }, moreActionsButton
    ]);
  },
  onHomeButtonTap: function() {
    return this.fireEvent('homeButtonTap');
  },
  onCreateEventButtonTap: function() {
    return this.fireEvent('createEventButtonTap');
  }
});
