// Generated by CoffeeScript 1.3.3

Ext.application({
  name: 'WSI',
  requires: ['Ext.plugin.ListPaging', 'Ext.form.FieldSet', 'Ext.form.Panel', 'Ext.field.TextArea', 'Ext.field.Email', 'Ext.field.Search', 'Ext.field.Password', 'Ext.Anim', 'WSI.plugin.BetterPullRefresh', 'WSI.store.Events'],
  stores: ['EventsCurrent', 'EventsPast', 'EventsFuture', 'EventsSearch', 'EventsMap', 'WhosThere'],
  controllers: ['Events', 'Account'],
  views: ['Main', 'TopToolbar'],
  launch: function() {
    Ext.Viewport.add([Ext.create('WSI.view.TopToolbar'), Ext.create('WSI.view.Main')]);
    return document.getElementById('images-to-preload').innerHTML = "";
  }
});
