// Generated by CoffeeScript 1.3.3

Ext.define('WSI.store.Events', {
  extend: 'Ext.data.Store',
  requires: ['WSI.model.Event'],
  config: {
    model: 'WSI.model.Event',
    pageSize: 20,
    autoLoad: true,
    proxy: {
      type: 'ajax',
      url: 'http://wesawit.com/event/get_events_mobile',
      extraParams: {
        'api_version': util.API_VERSION,
        'token': window.localStorage.getItem('wsitoken'),
        'uid': window.localStorage.getItem('uid'),
        category: 'all',
        country: 'world'
      },
      reader: {
        type: 'json',
        rootProperty: 'events'
      }
    },
    listeners: {
      beforeload: function(store) {
        store.lastTimeLoadCalled = new Date();
        store.getProxy().config.extraParams.token = window.localStorage.getItem('wsitoken');
        store.getProxy().config.extraParams.uid = window.localStorage.getItem('uid');
        store.getProxy().config.extraParams.locationLat = window.localStorage.getItem('locationLat');
        store.getProxy().config.extraParams.locationLng = window.localStorage.getItem('locationLng');
        store.getProxy().config.extraParams.locationTimestamp = window.localStorage.getItem('locationTimestamp');
        return true;
      },
      load: function(store, records, successful, operation) {
        var _ref;
        if ((((_ref = operation.getResponse()) != null ? _ref.timedout : void 0) != null) && operation.getResponse().timedout === true) {
          navigator.notification.alert('Your internet connection seems to be going too slow.', (function() {}), 'Hmm...');
        }
        return true;
      }
    }
  }
});
