// Generated by CoffeeScript 1.3.3

Ext.define('WSI.store.WhosThere', {
  extend: 'Ext.data.Store',
  xtype: 'whostherestore',
  requires: ['WSI.model.Who'],
  config: {
    model: 'WSI.model.Who',
    pageSize: 100,
    autoLoad: false,
    proxy: {
      type: 'ajax',
      url: 'http://wesawit.com/event/who',
      extraParams: {
        'api_version': util.API_VERSION,
        'uid': window.localStorage.getItem('uid'),
        'eid': '0'
      },
      reader: {
        type: 'json',
        rootProperty: 'data'
      }
    },
    listeners: {
      beforeload: function(store) {
        store.getProxy().config.extraParams.uid = window.localStorage.getItem('uid');
        return true;
      },
      load: function(s, records, successful, operation) {
        var _ref;
        if ((((_ref = operation.getResponse()) != null ? _ref.timedout : void 0) != null) && operation.getResponse().timedout === true) {
          navigator.notification.alert('Your internet connection seems to be going too slow.', (function() {}), 'Hmm...');
        }
        return true;
      }
    }
  }
});
