// Generated by CoffeeScript 1.3.3

Ext.define('WSI.model.Media', {
  extend: 'Ext.data.Model',
  config: {
    fields: [
      {
        name: 'id',
        type: 'string'
      }, {
        name: 'pid',
        type: 'string'
      }, {
        name: 'vid',
        type: 'string'
      }, {
        name: 'xid',
        type: 'string'
      }, {
        name: 'event_id',
        type: 'string'
      }, {
        name: 'aeid',
        type: 'string'
      }, {
        name: 'author',
        type: 'string'
      }, {
        name: 'authorUid',
        type: 'string'
      }, {
        name: 'viewCount',
        type: 'int'
      }, {
        name: 'worthinessCount',
        type: 'int'
      }, {
        name: 'deemed_worthy_by_me',
        type: 'boolean',
        defaultValue: false
      }, {
        name: 'flagged_by_me',
        type: 'boolean',
        defaultValue: false
      }, {
        name: 'mobileOrigin',
        type: 'int'
      }, {
        name: 'thumbUrl',
        type: 'string'
      }, {
        name: 'mediumUrl',
        type: 'string'
      }, {
        name: 'url',
        type: 'string'
      }, {
        name: 'status',
        type: 'string',
        convert: function(v, rec) {
          if (v === 'uploading') {
            return 'uploading';
          } else if (v === 'processing') {
            return 'processing';
          } else {
            return 'loaded';
          }
        }
      }, {
        name: 'timestampTaken',
        convert: function(v, rec) {
          var arr, d;
          if (typeof v === 'string') {
            arr = v.split(/[- :\.]/);
            d = new Date();
            d.setUTCFullYear(parseInt(arr[0]));
            d.setUTCMonth(parseInt(arr[1]) - 1);
            d.setUTCDate(parseInt(arr[2]));
            d.setUTCHours(parseInt(arr[3]));
            d.setUTCMinutes(parseInt(arr[4]));
            d.setUTCSeconds(parseInt(arr[5]));
            return d;
          } else {
            return v;
          }
        }
      }
    ]
  }
});
