// Generated by CoffeeScript 1.3.3

Ext.define('WSI.model.Who', {
  extend: 'Ext.data.Model',
  config: {
    fields: [
      {
        name: 'id',
        type: 'string'
      }, {
        name: 'username',
        type: 'string'
      }, {
        name: 'medias',
        convert: function(v, rec) {
          var arr, i, _i, _len, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6;
          for (_i = 0, _len = v.length; _i < _len; _i++) {
            i = v[_i];
            if ((_ref = i.pid) == null) {
              i.pid = null;
            }
            if ((_ref1 = i.vid) == null) {
              i.vid = null;
            }
            if ((_ref2 = i.xid) == null) {
              i.xid = null;
            }
            if ((_ref3 = i.file_ext) == null) {
              i.file_ext = null;
            }
            if ((_ref4 = i.status) == null) {
              i.status = 'loaded';
            }
            if ((_ref5 = i.webHeight) == null) {
              i.webHeight = null;
            }
            if ((_ref6 = i.webWidth) == null) {
              i.webWidth = null;
            }
            arr = i.timestampTaken.split(/[- :\.]/);
            i.timestampTaken = new Date();
            i.timestampTaken.setUTCFullYear(parseInt(arr[0]));
            i.timestampTaken.setUTCMonth(parseInt(arr[1]) - 1);
            i.timestampTaken.setUTCDate(parseInt(arr[2]));
            i.timestampTaken.setUTCHours(parseInt(arr[3]));
            i.timestampTaken.setUTCMinutes(parseInt(arr[4]));
            i.timestampTaken.setUTCSeconds(parseInt(arr[5]));
          }
          return v;
        }
      }
    ]
  }
});
